repos:
  - repo: local
    hooks:
      - id: gitlint-commit-msg
        name: gitlint commit message
        entry: poetry run gitlint --msg-filename
        language: system
        stages: [commit-msg]
